default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: gabriel
  password: 123456

development:
  <<: *default
  database: finance_wallet_development

production:
  <<: *default
  database: finance_wallet_production

test:
  <<: *default
  host: localhost
  database: db/finance_wallet_test
  password: 123456